version: '3'
services:
  nginx:
    image: nginx:1.13.7
    container_name: nginx
    restart: always
    depends_on:
      - php-fpm
      - flask
      - mariadb
    volumes:
      - ./site:/src
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  flask:
    restart: always
    build:
      context: .
      dockerfile: ./image/python/Dockerfile
    container_name: flask
    volumes:
      - ./flask:/app/
    environment:
      - FLASK_APP=/app/main.py
    command: flask run --host=0.0.0.0
    ports:
      - 8080:5000

  mariadb:
    container_name: mariadb
    image: mariadb:10.3
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
      - 8705:80
    environment:
      MYSQL_ROOT_PASSWORD: 123
    depends_on:
      - mariadb
    networks:
      - default

  php-fpm:
    container_name: php
    build: ./image/php
    links:
      - mariadb
      #- postgres
    ports:
      - "9000:9000"
    volumes:
      - ./site:/src
